#!/usr/bin/env python3
import sys

# function to write file with new text
def write_to_file(filename, string):

    try:
        with open(filename, "w") as file:
            file.write(string)
        return f"Successfully wrote to file: {filename}"
    except Exception as e:
        return f"Error writing to file {filename}: {e}"

# function to remove consecutive new lines from a string
def remove_new_line(string):

    bool_flag = False
    new_string = ""
    for char in string:
        if char == "\n":
            if not bool_flag:
                new_string += char
            bool_flag = True
        else:
            new_string += char
            bool_flag = False
    return new_string

# function to process file and return its contents
def process_file(filename):

    try:
        with open(filename, "r") as file:
            content = file.read()
    except FileNotFoundError:
        print(f"Error: {filename} not found")
        sys.exit(1)
    return content

# main function
def main():
    
    # get the content of the file
    if len(sys.argv) != 2:
        print("Invalid argument")
        sys.exit(1)

    filename = sys.argv[1]
    string = process_file(filename)
    new_string = remove_new_line(string)
    message = write_to_file(filename, new_string)
    print(message)

# start program
if __name__ == "__main__":
    
    main()
